### ISSUE TITLE
car plugged in entity missing?

### ISSUE THREAD

**Issue by domerich** [syssi/homeassistant-goecharger-mqtt#81]
Hello is there an entity available if a car is plugged in? in this integration I cannot find it, it seems:

sensor.goecharger_garage_rechts**_cable_lock_mode**

in the other integration I can see with this if a car is plugged in

**Comment by syssi** [comment]
I will have a look.

**Comment by syssi** [comment]
It's called "cable unlock mode" here.

**Comment by domerich** [comment]
> cable unlock mode

I dont think so with cable unlock mode I can select how to unlock

_cable_lock_mode** gave me the info if any car is plugged into the wallbox. I would like to have this info

**Comment by syssi** [comment]
Are you sure about the name of the other entity? Do you mean `car state` may be?

**Comment by syssi** [comment]
A may be you are looking for `cable lock status` (cus). This entity is disabled per default an can be found and enabled at the hidden section of the device page.

**Comment by domerich** [comment]
No this entity is not there even down there with the hidden ones

**Comment by syssi** [comment]
I've released a new version. The `Cable unlock status` sensor should be available now if you update to version `0.16.0`.

**Comment by domerich** [comment]
sorry this is still not the right entity. I do not want to know if the cable is locked but if a cable is plugged in.

**Comment by syssi** [comment]
Is the `car state` what you are looking for?

**Comment by nilrog** [comment]
Afaik this is the `car` entity in the v2 API. If the cable is disconnected/unplugged from the car it will be in "Idle". If plugged in it will be in any of the other states depending on if the car is charging etc.

**Comment by syssi** [comment]
I could introduce a `binary_sensor` which maps the values to a boolean and call the sensor `car_detected` if this is helpful.

**Comment by domerich** [comment]
maybe you guys could just steal it from the other integration :D I wanted to make such automation to heat up the house more if no cars are plugged in in the garages and their batteries is <90%

**Comment by nilrog** [comment]
You can easily do that with what is available from this integration today. There is no need, imo, to add more sensors. That will only make you dependent on the integration to implement things. When instead you have the power of home assistant to do whatever you want :)

The condition you need to check in an automation, triggered by something else, to see if the car is unplugged is this:

```
- condition: state
  entity_id: sensor.go_echarger_123456_car
  state: "Idle"
```

Or, if you want to **trigger** an automation when the car becomes unplugged you can use this as trigger:

```
- platform: state
  entity_id: sensor.go_echarger_123456_car
  to: "Idle"
```

**Comment by domerich** [comment]
yeah I guess that works, I just liked the yellow plug symbol so I could tell that my wife plugged in her car.

**Comment by woopstar** [comment]
@syssi is it also possible to get the car SoC through Go-E ? So you do not need to have a EV integration also for your Audi, Skoda, Tesla or whatever.

**Comment by woopstar** [comment]
> The short answer is "no". The go-eCharger APIv2 doesn't provide this information probably because the information isn't available via a Type 2 plug. This is the API description of the manufacturer: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md

I see. But available from DC? I see that some charging stations show the SoC on screens, so it must be available in some cases.
